
// Generated by Codex tool
import { testAdd } from './test-claude';

describe('testAdd', () => {
  it('returns the sum of two numbers', () => {
    expect(testAdd(2, 3)).toBe(5);
    expect(testAdd(-1, 1)).toBe(0);
    expect(testAdd(0, 0)).toBe(0);
  });
});
